### ISSUE TITLE
Invalid main/module/exports in package json

### ISSUE THREAD

**Issue by yharaskrik** [upstash/semantic-cache#6]
Trying to run with vite-node causes this error. Seems like maybe the package json isn't quite right?

It looks like the published version is missing the file in the `module` field

`"module": "./dist/index.mjs",`

```
3:50:12 PM [vite] Pre-transform error: Failed to resolve entry for package "@upstash/semantic-cache". The package may have incorrect main/module/exports specified in its package.json.
file:///Users/jaybell/.npm/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:46637
  const err = new Error(
              ^

Error: Failed to resolve entry for package "@upstash/semantic-cache". The package may have incorrect main/module/exports specified in its package.json.
    at packageEntryFailure (file:///Users/jaybell/.npm/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:46637:15)
    at resolvePackageEntry (file:///Users/jaybell/.npm/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:46634:3)
    at tryNodeResolve (file:///Users/jaybell/.npm/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:46450:16)
    at ResolveIdContext.resolveId (file:///Users/jaybell/.npm/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:46200:19)
    at PluginContainer.resolveId (file:///Users/jaybell/.npm/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:49015:17)
    at processTicksAndRejections (node:internal/process/task_queues:105:5)
    at TransformPluginContext.resolve (file:///Users/jaybell/.npm/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:49175:15)
    at normalizeUrl (file:///Users/jaybell/.npm/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:64034:26)
    at file:///Users/jaybell/.npm/_npx/f2342a4b64a2bc92/node_modules/vite/dist/node/chunks/dep-CB_7IfJ-.js:64173:39
    at async Promise.all (index 3) {

```

**Comment by yharaskrik** [comment]
If i remove the `module` prop from the package.json it works.

**Comment by ytkimirti** [comment]
Yes you are right, I will open a PR for fixing this asap

**Comment by ytkimirti** [comment]
Hey @yharaskrik, we published a new version. Can you try bumping to 1.0.5?
